<application>
  <component name="ActionsCollector">
    <counts>
      <entry action="$Copy" count="10" />
      <entry action="$Cut" count="20" />
      <entry action="$Delete" count="244" />
      <entry action="$Paste" count="103" />
      <entry action="$SelectAll" count="30" />
      <entry action="$Undo" count="2459" />
      <entry action="Android.CreateResourceDirectory" count="12" />
      <entry action="Android.CreateSampleDataDirectory" count="6" />
      <entry action="Android.GenerateSignedApk" count="4" />
      <entry action="Android.LinkExternalCppProject" count="1" />
      <entry action="Android.RunAndroidAvdManager" count="2" />
      <entry action="Android.RunAndroidSdkManager" count="3" />
      <entry action="Android.ShowThemeEditor" count="1" />
      <entry action="Android.SyncProject" count="1" />
      <entry action="AndroidMigrateToAndroidxAction" count="18" />
      <entry action="AndroidMigrateToAppCompatAction" count="1" />
      <entry action="ChooseDebugConfiguration" count="1" />
      <entry action="ChooseRunConfiguration" count="2" />
      <entry action="ClassNameCompletion" count="1" />
      <entry action="CleanGradleProject" count="2" />
      <entry action="CodeCompletion" count="1" />
      <entry action="CollapseSelection" count="1" />
      <entry action="CommentByBlockComment" count="9" />
      <entry action="CommentByLineComment" count="3" />
      <entry action="CompareTwoFiles" count="5" />
      <entry action="Debug" count="4" />
      <entry action="DeveloperServices.Firebase" count="31" />
      <entry action="DialogOkAction Ctrl" count="1" />
      <entry action="DialogOkAction Enter" count="107" />
      <entry action="EditSource" count="1" />
      <entry action="EditorBackSpace" count="59821" />
      <entry action="EditorChooseLookupItem" count="9210" />
      <entry action="EditorCodeBlockEnd" count="1" />
      <entry action="EditorCodeBlockStart" count="2" />
      <entry action="EditorCopy" count="263" />
      <entry action="EditorCut" count="359" />
      <entry action="EditorDown" count="12935" />
      <entry action="EditorDownWithSelection" count="34" />
      <entry action="EditorDuplicate" count="4" />
      <entry action="EditorEnter" count="4328" />
      <entry action="EditorEscape" count="2" />
      <entry action="EditorLeft" count="1283" />
      <entry action="EditorLeftWithSelection" count="1305" />
      <entry action="EditorLineEnd" count="3" />
      <entry action="EditorLineStart" count="21" />
      <entry action="EditorNextWord" count="1" />
      <entry action="EditorNextWordWithSelection" count="1" />
      <entry action="EditorPageDown" count="7" />
      <entry action="EditorPaste" count="817" />
      <entry action="EditorPreviousWord" count="8" />
      <entry action="EditorRight" count="4254" />
      <entry action="EditorRightWithSelection" count="797" />
      <entry action="EditorSelectWord" count="2" />
      <entry action="EditorSplitLine" count="13" />
      <entry action="EditorStartNewLine" count="7" />
      <entry action="EditorStartNewLineBefore" count="15" />
      <entry action="EditorTab" count="23" />
      <entry action="EditorToggleInsertState" count="7" />
      <entry action="EditorUp" count="5377" />
      <entry action="EditorUpWithSelection" count="71" />
      <entry action="ExpandRegion" count="1" />
      <entry action="ExportSettings" count="1" />
      <entry action="FileChooser.Delete" count="10" />
      <entry action="FileChooser.NewFolder" count="1" />
      <entry action="Find" count="1" />
      <entry action="Generate" count="20" />
      <entry action="GotoBookmark1" count="2" />
      <entry action="GotoBookmark8" count="1" />
      <entry action="GotoDeclaration" count="8" />
      <entry action="GotoFile" count="1" />
      <entry action="HideAllWindows" count="36" />
      <entry action="Images.Editor.ToggleGrid" count="1" />
      <entry action="Images.Editor.ZoomOut" count="7" />
      <entry action="ImportApkAction" count="2" />
      <entry action="ImportSettings" count="1" />
      <entry action="IntroduceVariable" count="35" />
      <entry action="MakeGradleProject" count="3" />
      <entry action="Migrate" count="2" />
      <entry action="NewAndroidImageAsset" count="2" />
      <entry action="NewClass" count="28" />
      <entry action="NewDir" count="6" />
      <entry action="NewFile" count="1" />
      <entry action="NewProject" count="122" />
      <entry action="NextTemplateVariable" count="82" />
      <entry action="OpenFile" count="264" />
      <entry action="OverrideMethods" count="2" />
      <entry action="Progress Paused" count="1" />
      <entry action="Progress Resumed" count="2" />
      <entry action="RebuildGradleProject" count="12" />
      <entry action="RecentChangedFiles" count="1" />
      <entry action="RecentFiles" count="3" />
      <entry action="RenameFile" count="1" />
      <entry action="Run" count="1173" />
      <entry action="SaveAll" count="249" />
      <entry action="SearchEverywhere" count="3" />
      <entry action="SelectIn" count="1" />
      <entry action="ShowErrorDescription" count="8" />
      <entry action="ShowIntentionActions" count="570" />
      <entry action="ShowPopupMenu" count="1" />
      <entry action="Sho